### ISSUE TITLE
Cannot find module lodash/defaultsDeep' and lodash/pullAll'

### ISSUE THREAD

**Issue by LogicalOgbonna** [hurkanyakay/reactjs-nodejs-rest-example#2]
node ./internals/scripts/dependencies.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\ARINZE PC\Documents\React-Real-Apps\Login-SignUp-MERN\reactjs-nodejs-rest-example-master\reactjs-nodejs-rest-example-master\FrontEnd\internals\scripts\dependencies.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hurkanyakay** [comment]
@LogicalOgbonna thank you for the notice, i am checking now
